/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-DMKlohcV-MpsgCH18tsoXA6Pha2RLxrvfYj-k1xuEKQ6EU9f0vDPx--Fr0MciXXSxyMh7OX2VPpoF5AQce2n2OvyJ-PQSbW2iyqWBG-Wbz-05crSKn5BpI9E",
  "tt": "tt-1-XjWvVa37d-ZiKWxYJgoLFW0E6Vjw9cQV-nlUxWztnuA=",
  "version": "2020-11-20"
}

export default ebconfig;